[package]
name = "komorebic"
version = "0.1.0"
edition = "2024"

[dependencies]
komorebi-client = { path = "../komorebi-client", default-features = false }

clap = { workspace = true }
color-eyre = { workspace = true }
dirs = { workspace = true }
lazy_static = { workspace = true }
pastey = { workspace = true }