[package]
name = "komorebi"
version = "0.1.0"
description = "A tiling window manager for macOS"
edition = "2024"

[dependencies]
clap = { workspace = true }
color-eyre = { workspace = true }
crossbeam-channel = "0.5"
ctrlc = { version = "3", features = ["termination"] }
dirs = { workspace = true }
hotwatch = "0.5"
lazy_static = { workspace = true }
nanoid = "0.4"
objc2 = "0.6"
objc2-app-kit = "0.3"
objc2-application-services = "0.3"
objc2-core-foundation = { version = "0.3", features = ["CFDictionary", "CFString"] }
objc2-core-graphics = { version = "0.3", features = ["CGWindow", "alloc"] }
objc2-foundation = "0.3"
parking_lot = "0.12"
pastey = { workspace = true }
quick-xml = { version = "0.38", features = ["serialize"] }
# forked to patch in serde_json_lenient and update some old dependencies
quickxml_to_serde = { git = "https://github.com/LGUG2Z/quickxml_to_serde.git", version = "0.6.1" }
regex = "1"
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = "3"
shadow-rs = { workspace = true }
strum = { version = "0.27", features = ["derive"] }
sysinfo = { workspace = true }
thiserror = { workspace = true }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
shadow-rs = { workspace = true }