[package]
name = "komorebi"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
color-eyre = { workspace = true }
crossbeam-channel = "0.5"
ctrlc = { version = "3", features = ["termination"] }
dirs = { workspace = true }
lazy_static = { workspace = true }
objc2 = "0.6"
objc2-app-kit = "0.3"
objc2-application-services = "0.3"
objc2-core-foundation = { version = "0.3", features = ["CFDictionary", "CFString"] }
objc2-core-graphics = { version = "0.3", features = ["CGWindow", "alloc"] }
parking_lot = "0.12"
pastey = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = "3"
strum = { version = "0.27", features = ["derive"] }
thiserror = { workspace = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }